#!/usr/bin/env zsh

alias -g G='| grep'
alias -g L='| less'
alias -g M='| most'
alias -g C='| wl-copy'
alias -g W='--watch'
alias -g H='| head'
alias -g F='| tail'
alias -g TF='| tail -f'
alias -g NUL='> /dev/null 2>&1'

alias -s pdf='firefox '
alias -s jpg='firefox '
alias -s png='firefox '
alias -s txt='cat '
alias -s md='cat '

alias '..'='cd ..'
alias '...'='cd ../..'
alias '....'='cd ../../..'

alias d='dirs -v'
for index in $(seq 1 9); do alias "$index"="cd +${index}"; done

alias reload-zsh='source "$ZDOTDIR/.zshrc"'
alias tmp='cd $(mktemp -d)'
alias uuid='uuid | tr -d "\n" C'
alias k9s='k9s --readonly'
alias h='http --session /tmp/http-session.json'

alias v='nvim'
alias g='git'
alias py='python'
alias t='true'

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias ls='ls --color=auto'
alias l='ls -lh'
alias ll='l -A'

alias paci='sudo pacman -S'
alias pacs='sudo pacman -Ss'
alias pacu='sudo pacman -Syu'
alias pacr='sudo pacman -Rs'

alias yays='yay -Ss'
alias yayi='yay -S --noconfirm'
alias yayu='yay -Syu --noconfirm'

alias sc='sudo systemctl'
alias sc-start='sc start'
alias sc-stop='sc stop'
alias sc-restart='sc restart'
alias sc-enable='sc enable'
alias sc-disable='sc disable'
alias sc-status='sc status'
alias sc-daemon-reload='sc daemon-reload'

alias scu='systemctl --user'
alias scu-start='scu start'
alias scu-stop='scu stop'
alias scu-restart='scu restart'
alias scu-enable='scu enable'
alias scu-disable='scu disable'
alias scu-status='scu status'
alias scu-daemon-reload='scu daemon-reload'

alias p='pnpm'
alias pt='pnpm run test'
alias ptw='pnpm run test --watch'
alias pb='pnpm build'
alias ptc='pnpm tsc --noEmit'
alias pl='pnpm lint'
alias pd='pnpm dev'
alias ps='pnpm start'
alias psw='pnpm start --watch'
alias pup='pnpm up -iL'
alias pa='pnpm add'
alias pad='pnpm add -D'
alias pr='pnpm remove'
alias psb='pnpm storybook'
