calendar_day_prefix_url: https://calendar.google.com/calendar/r/day/
change_icon_minutes: 5
default_icon: "\u2023"
event_organizers_icon: {}
max_results: 10
my_emails: []
restrict_to_calendar: []
skip_all_day: false
skip_non_accepted: false
skip_non_confirmed: false
starts_today_only: true
strip_title_emojis: false
title_match_icon: {}
title_max_char: 20
verbose: false
