" Global config
" =============

set nocompatible
set expandtab
set softtabstop=2
set shiftwidth=2
set laststatus=2
set encoding=utf-8
set colorcolumn=80

syntax on
filetype off

" Vundle plugins manager
" ======================

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'godlygeek/tabular'
Plugin 'scrooloose/syntastic'
Plugin 'kien/ctrlp.vim'
Plugin 'Lokaltog/vim-powerline'

call vundle#end()

" Plugins configuration

filetype plugin indent on

" Custom mappings
" ===============

noremap T 8<Down>
noremap N 8<Up>

noremap l n
noremap L N

nmap ; :CtrlPBuffer<CR>

nmap <C-L> :set invnumber<CR>:set invrelativenumber<CR>

" Other
" =====

highlight LineNr ctermfg=DarkGrey ctermbg=NONE
set listchars=tab:>-,trail:-
set list
